cursor #1c1b1a
cursor_text_color #4a463e

foreground            #1c1b1a
background            #fdf8f6
selection_foreground  #ffffff
selection_background  #cbc6be
url_color             #635e50

color0   #141312
color1   #793630
color2   #2a5f21
color3   #998626
color4   #676253
color5   #afaca4
color6   #635e50
color7   #232322
color8   #6c6b69
color9   #a35c54
color10  #4a8c3f
color11  #a59231
color12  #756f5d
color13  #afaca4
color14  #807d74
color15  #bfbebb
