cursor #e6e2df
cursor_text_color #ccc6bb

foreground            #e6e2df
background            #141312
selection_foreground  #33302b
selection_background  #cbc6be
url_color             #fdf4e3

color0   #141312
color1   #ff7d72
color2   #91fd7e
color3   #ffe772
color4   #f0e6d2
color5   #756d5f
color6   #fdf4e3
color7   #fff9ef
color8   #a49f98
color9   #ffa69f
color10  #b3ffa5
color11  #fff0a5
color12  #fff7e8
color13  #fff8ec
color14  #fffaf3
color15  #fffcf8
