window_padding_width 5
hide_window_decorations yes
background_opacity 0.5
font_family ComicShannsMono Nerd Font
font_size 14
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1
cursor_shape block
shell_integration no-cursor
