# theme = "vim_dark_high_contrast"
# theme = "peachpuff"
theme = "tokyonight"

[keys.insert]
j = { k = "normal_mode"}

[keys.normal]
H = "goto_first_nonwhitespace"
L = "goto_line_end"

[editor]
true-color = true
idle-timeout = 220
line-number = "relative"
# bufferline = "multiple"
bufferline = "never"
cursorline = true
continue-comments = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = false
auto-signature-help = true
display-inlay-hints = false
display-color-swatches = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true
